# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Desktop/Study_now/SRW/GoertzelAlgorithm/vivado/project/SRW.srcs/sources_1/ip/gtwizard_ultrascale/gtwizard_ultrascale.xci
# IP: The module: 'gtwizard_ultrascale' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/Study_now/SRW/GoertzelAlgorithm/vivado/project/SRW.srcs/sources_1/ip/gtwizard_ultrascale/synth/gtwizard_ultrascale_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Desktop/Study_now/SRW/GoertzelAlgorithm/vivado/project/SRW.srcs/sources_1/ip/gtwizard_ultrascale/synth/gtwizard_ultrascale.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Desktop/Study_now/SRW/GoertzelAlgorithm/vivado/project/SRW.srcs/sources_1/ip/gtwizard_ultrascale/gtwizard_ultrascale.xci
# IP: The module: 'gtwizard_ultrascale' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/Study_now/SRW/GoertzelAlgorithm/vivado/project/SRW.srcs/sources_1/ip/gtwizard_ultrascale/synth/gtwizard_ultrascale_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Desktop/Study_now/SRW/GoertzelAlgorithm/vivado/project/SRW.srcs/sources_1/ip/gtwizard_ultrascale/synth/gtwizard_ultrascale.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
